CREATE TABLE IF NOT EXISTS users (
 username VARCHAR(64) PRIMARY KEY,
 email VARCHAR(64) UNIQUE NOT NULL,
 password VARCHAR(64) NOT NULL);
 
CREATE TABLE IF NOT EXISTS petsitters (
  username VARCHAR(64) PRIMARY KEY REFERENCES users (username),
  startDate DATE,
  endDate DATE,
  price NUMERIC NOT NULL,
  dog BOOLEAN NOT NULL DEFAULT FALSE,
  cat BOOLEAN NOT NULL DEFAULT FALSE,
  petBoarding BOOLEAN NOT NULL DEFAULT FALSE,
  dogWalking BOOLEAN NOT NULL DEFAULT FALSE,
  petGrooming BOOLEAN NOT NULL DEFAULT FALSE,
  petDaycare BOOLEAN NOT NULL DEFAULT FALSE,
  petSitting BOOLEAN NOT NULL DEFAULT FALSE,
  petTaxi BOOLEAN NOT NULL DEFAULT FALSE);

CREATE TABLE IF NOT EXISTS jobs (
  id SERIAL PRIMARY KEY,
  hirer_username VARCHAR(64),
  sitter_username VARCHAR(64),
  status VARCHAR(20) NOT NULL DEFAULT 'In Progress');